# creating numpy array basic numpy built-in methods

In [ ]:
#np.zeros - returns an array with 0 only
#np.ones - returns an array with 1 only
#np.full - array with desired number
#np.full((row,col),desired no)
#np.eye - identity matrix
#np.arange - similar to range function
#np.linspace - evenly divides the array

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr2=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.full((4,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [8]:
np.full((3,5),9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

# Identity matrix

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [13]:
np.linspace(655,876,7)

array([655.        , 691.83333333, 728.66666667, 765.5       ,
       802.33333333, 839.16666667, 876.        ])

# Checking array properties

In [ ]:
#arr.shape - return shape of array
#arr.size - return total element
#arr.ndim - return dimension of array
#arr.dtype - return data type
#type(arr) - return array dimension

In [14]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
arr.shape

(4, 3)

In [16]:
arr.size

12

In [17]:
arr.ndim

2

In [18]:
arr=np.array([1,2,3,4,5])
arr.ndim

1

In [21]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [22]:
arr.ndim

3

In [23]:
arr.dtype

dtype('int64')

In [24]:
arr=np.zeros((3,3))
arr.dtype

dtype('float64')

# Changing data type

In [26]:
arr=np.array([1.1,2.2,3.3],dtype=np.int32)
arr

array([1, 2, 3], dtype=int32)

In [27]:
arr=np.array([1.1,2.2,3.3])
arr1=arr.astype(np.int64)
arr

array([1.1, 2.2, 3.3])

In [28]:
arr=np.array([1,2,3,4],dtype="float64")
arr

array([1., 2., 3., 4.])

In [29]:
arr1=arr.astype("int64")
arr1

array([1, 2, 3, 4])

In [30]:
arr1=arr.astype("int32")
arr1

array([1, 2, 3, 4], dtype=int32)

In [31]:
arr1.dtype

dtype('int32')

# Reshaping & flattening the array

In [32]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
arr.shape

(4, 3)

In [34]:
arr.size

12

In [35]:
my_arr=arr.reshape(3,4)
my_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [37]:
arr.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [39]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])