In [4]:
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr1=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr1)
arr1.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


3

In [11]:
a3=np.array([[1,2],[3,4],['5','6']])  # convert all values in str format
print(a3)

[['1' '2']
 ['3' '4']
 ['5' '6']]


In [14]:
a3=np.array([[1,2],[3.,4.],[5,6]])  #if u put 1 float it will convert all float
print(a3)
a3.ndim

[[1. 2.]
 [3. 4.]
 [5. 6.]]


2

In [21]:
a3=np.array([[1,2],[3.,4],[5,6]])
print(a3)
print(a3.dtype)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
float64


In [20]:
a4=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(a4)
a4.ndim
a4.dtype

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


dtype('int64')

# Declaration of datatype

In [31]:
a3=np.array([1,2,3],dtype='i4')
a3

array([1, 2, 3], dtype=int32)

In [32]:
a5=np.array([1,2,3],dtype='int32')
a5

array([1, 2, 3], dtype=int32)

In [33]:
a5=np.array([1,2,3],dtype='f4')
a5

array([1., 2., 3.], dtype=float32)

In [34]:
a5=np.array([1,2,3],dtype='S')
a5

array([b'1', b'2', b'3'], dtype='|S1')

In [36]:
a5=np.array([1,'2',3.5])
a5

array(['1', '2', '3.5'], dtype='<U32')