# Multidimensional array

In [1]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [2]:
arr.shape

(4, 3)

In [5]:
arr[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [6]:
arr[1:4,1:3]

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [7]:
arr[1:1,1:1]

array([], shape=(0, 0), dtype=int64)

# 3D Array - multiple 2D array are stacked together

In [10]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [11]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
arr[ : ,0, : ]


array([[1, 2, 3],
       [7, 8, 9]])

# Built mathematical function

In [14]:
#np.mean() - compute the mean(Avg) of array
#np.min()- return a minimum value in array
#np.max()- return a max val in array
#np.std()- return a standerd deviation(is a measure of how spreaded out the val in data from mean)

    #SD=sqrt((sum(xi-N)^2))%N

#xi=chace value
#u=mean
#N=total number of value

#np.var()- return a variance of array
#variance- measure the avg of sqr different from mean

In [25]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
np.sum(arr)

np.int64(78)

In [27]:
np.prod(arr)

np.int64(479001600)

In [28]:
arr[1,2]

np.int64(6)

In [29]:
np.median(arr)

np.float64(6.5)

In [30]:
#np.percentile()- compute the percentile of array
    #50th percentile=median
    #25th percentile=first quartile(Q1)
    #75th percentile=3rd quartile(Q1)
#np.argmin()- return the index num of min val in array
#np.argmax()- return the index num of max val in array

In [31]:
np.percentile(arr,50)

np.float64(6.5)

In [32]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
np.argmin(arr)

np.int64(0)

In [34]:
np.argmax(arr)

np.int64(11)

In [35]:
x=[1,2,3]
y=[2,4,6]
np.corrcoef(x,y)

array([[1., 1.],
       [1., 1.]])

In [36]:
x=[1,2,3]
y=[8,6,4]
np.corrcoef(x,y)

array([[ 1., -1.],
       [-1.,  1.]])

In [37]:
x=[1,2,3]
y=[5,1,8]
np.corrcoef(x,y)

array([[1.       , 0.4271211],
       [0.4271211, 1.       ]])

In [38]:
arr1=np.array([1,2,3,4,5,2,4,6,4,2])
np.unique(arr1)

array([1, 2, 3, 4, 5, 6])

In [39]:
np.diff(arr)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [40]:
np.cumsum(arr1)  #cumulitives

array([ 1,  3,  6, 10, 15, 17, 21, 27, 31, 33])

In [41]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])